// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaGIWufENjsIdupHI3hYLlL85zo5HE_SU',
    appId: '1:670817824904:web:7fb21a531467be7557af3d',
    messagingSenderId: '670817824904',
    projectId: 'skillsconnect-7ba2d',
    authDomain: 'skillsconnect-7ba2d.firebaseapp.com',
    storageBucket: 'skillsconnect-7ba2d.firebasestorage.app',
    measurementId: 'G-GEB36W72SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCim4AYKO3RffkAjDxEryC7tqNlsVK8S8',
    appId: '1:670817824904:android:44047e03364e26ad57af3d',
    messagingSenderId: '670817824904',
    projectId: 'skillsconnect-7ba2d',
    storageBucket: 'skillsconnect-7ba2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbW0CfnBgCPuHgdFy4QPD5u6xB7YX9spk',
    appId: '1:670817824904:ios:c646ee3510e64c5157af3d',
    messagingSenderId: '670817824904',
    projectId: 'skillsconnect-7ba2d',
    storageBucket: 'skillsconnect-7ba2d.firebasestorage.app',
    iosBundleId: 'com.skillsconnect.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbW0CfnBgCPuHgdFy4QPD5u6xB7YX9spk',
    appId: '1:670817824904:ios:c646ee3510e64c5157af3d',
    messagingSenderId: '670817824904',
    projectId: 'skillsconnect-7ba2d',
    storageBucket: 'skillsconnect-7ba2d.firebasestorage.app',
    iosBundleId: 'com.skillsconnect.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaGIWufENjsIdupHI3hYLlL85zo5HE_SU',
    appId: '1:670817824904:web:c2ba309b8624921e57af3d',
    messagingSenderId: '670817824904',
    projectId: 'skillsconnect-7ba2d',
    authDomain: 'skillsconnect-7ba2d.firebaseapp.com',
    storageBucket: 'skillsconnect-7ba2d.firebasestorage.app',
    measurementId: 'G-0995ZRMZ71',
  );

}